.devops/testing-pipeline.yml, api/enti.py, bdd/features/enti.feature, bdd/steps/enti_step.py, config/pu_feature_secrets_template.yaml, util/utility.py
=> feat: P4ADEV-463 new scenario of enti funzionalita

api/dovuti.py, api/enti.py, api/tipi_dovuto.py, api/utenti.py, config/pu_feature_secrets_template.yaml, settings.yaml
- added header "brokerId" for all api of PU
Run:
=> fix: P4ADEV-942 added new header for broker id

.devops/testing-pipeline.yml, api/dovuti.py, api/utenti.py, bdd/features/dovuti.feature, bdd/steps/dovuti_step.py, bdd/steps/tipi_dovuto_step.py, config/pu_feature_secrets_template.yaml, util/utility.py
- added other tests about dovuti
Run:
=> feat: P4ADEV-424 gestione dovuti

.devops/testing-pipeline.yml, api/auth.py, api/dovuti.py, api/enti.py, api/generic.py, api/soap/fesp.py, api/tipi_dovuto.py, api/utenti.py, config/pu_feature_secrets_template.yaml, settings.yaml
- added the possibility to run tests in UAT
Run:
=> chore: P4ADEV-849 initialize uat env

api/dovuti.py, api/utenti.py
=> fix: Fix url

api/soap/nodo.py, api/soap/requests_template/activatePaymentNotice.xml, api/soap/requests_template/sendPaymentOutcome.xml, api/soap/requests_template/verifyPaymentNotice.xml, bdd/steps/dovuti_step.py, config/pu_feature_secrets_template.yaml, settings.yaml
Fix scenario of payment dovuto using 'primitives' of nodo
Run:
=> fix: Fix scenario of payment dovuto using 'primitives' of nodo

bdd/steps/dovuti_step.py
=> fix: Fix avviso

api/soap/nodo.py
=> fix: Removed log

api/soap/nodo.py, bdd/steps/dovuti_step.py
- Modified the assertion of a test due to a change of exception in insert dovuto
Run:
=> fix: Fixed test after new activity in insert dovuto

bdd/steps/dovuti_step.py
=> fix: Fix desc error

api/dovuti.py
=> fix: Added new field ignorePdnd in insert dovuto

api/classifications.py, api/debt_positions.py, api/process_executions.py, bdd/features/debt_positions.feature, bdd/steps/authentication_step.py, bdd/steps/classification_step.py, bdd/steps/debt_positions_step.py, bdd/steps/payments_step.py, bdd/steps/utils/debt_position_utility.py, bdd/steps/utils/utility.py, bdd/steps/workflow_step.py, model/file.py, model/workflow_hub.py, settings.yaml
=> feat: P4ADEV-2696 payment of single installment

bdd/features/debt_positions.feature, bdd/steps/file_template/treasury_opi.xml, bdd/steps/payments_reporting_step.py, bdd/steps/payments_step.py, bdd/steps/treasury_step.py, model/workflow_hub.py, settings.yaml
=> feat: P4ADEV-2698 treasury test

.devops/testing-pipeline.yml, bdd/features/classification.feature, bdd/features/debt_positions.feature, bdd/steps/classification_step.py, bdd/steps/debt_positions_step.py, bdd/steps/gpd_aca_step.py, bdd/steps/payments_reporting_step.py, bdd/steps/treasury_step.py, bdd/steps/workflow_step.py
=> fix: Add test create dp simple

.devops/testing-pipeline.yml
=> fix: Fix pipeline

.devops/testing-pipeline.yml, api/send.py, bdd/features/send_notification.feature, bdd/steps/send_step.py
=> feat: P4ADEV-2950 test amount actualization post payment

bdd/features/classification.feature
=> fix: Fix scenario

api/debt_positions.py, bdd/features/classification.feature, bdd/steps/debt_positions_step.py, bdd/steps/payments_reporting_step.py, bdd/steps/payments_step.py, model/file.py, settings.yaml
=> feat: P4ADEV-3034 test 1.4 - payment reporting with dp and no receipt

api/debt_positions.py, bdd/features/debt_positions_file.feature, bdd/steps/debt_positions_file_step.py, bdd/steps/debt_positions_step.py, bdd/steps/gpd_aca_step.py, bdd/steps/payments_reporting_step.py, bdd/steps/payments_step.py, bdd/steps/treasury_step.py, bdd/steps/utils/debt_position_utility.py, bdd/steps/utils/utility.py, bdd/steps/workflow_step.py, model/csv_file_debt_positions.py, model/debt_position.py, model/workflow_hub.py, settings.yaml
=> feat: P4ADEV-2589 test import file debt position

.devops/testing-pipeline.yml, bdd/features/debt_positions_file.feature, bdd/steps/debt_positions_file_step.py, bdd/steps/debt_positions_step.py, model/csv_file_debt_positions.py
=> feat: P4ADEV-3050 test 2.1 - test file v1.4

bdd/steps/send_step.py
=> fix: P4ADEV-3262 modified create send notification with recipients array

.devops/testing-pipeline.yml, bdd/features/debt_positions_file.feature, behave.ini
=> feat: P4ADEV-3093 import file v1.3

.devops/testing-pipeline.yml, bdd/features/assessments.feature, bdd/steps/debt_positions_step.py, bdd/steps/file_template/payment_reporting.xml, bdd/steps/payments_reporting_step.py
=> feat: P4ADEV-3351 test 3.1 create assessment and assessment detail without balance input

bdd/steps/file_template/treasury_opi.xml, bdd/steps/send_step.py, bdd/steps/treasury_step.py, bdd/steps/utils/utility.py
=> fix: Fix treasury ingestion file

model/csv_file_debt_positions.py, model/debt_position.py
=> fix: Fix debt position ingestion file adding generateNotice

.devops/testing-pipeline.yml
=> fix: P4ADEV-3700 add schedule run test every day of week

bdd/steps/debt_positions_file_step.py
=> fix: Fix test ingestion dp
